### ISSUE TITLE
git clone https://bitbucket.org/admobilize/admobilize-gesture.git doesn't work

### ISSUE THREAD

**Issue by MarioFux** [matrix-io/matrix-gesture-node-sdk#1]
AdMobilize Gesture doesn't seem to work. git clone https://bitbucket.org/admobilize/admobilize-gesture.git doesn't work without a username and with one it doesn't work as well. The git repo doesn't seem to exist.

**Comment by lucasmoraisdev** [comment]
Hello @MarioFux please go to our GitHub repositories:
- https://github.com/matrix-io/matrix-os
- https://github.com/matrix-io/malos-eye

You can find examples of Gesture in malos-eye repo for example.
I will close this issue. Have a nice day.

**Comment by MarioFux** [comment]
Morning gordinh
Thanks for the quick answer. Unfortunately I get this error for malos-eye:
Err:4 http://packages.matrix.one/matrix-creator ./ Release
  404  Not Found [IP: 172.217.16.144 80]
Reading package lists... Done                     
E: The repository 'http://packages.matrix.one/matrix-creator ./ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by lucasmoraisdev** [comment]
Can you move this issue to the proper repository? Just to organize our issues :)

**Comment by MarioFux** [comment]
Ok, will move it in a second and thus close it here.
